### ISSUE TITLE
MessengerResult completion

### ISSUE THREAD

**Issue by Geminior** [tibel/Caliburn.Micro.Extras#7]
Hi,

In its present from a messenger result is never cancelled, so it can't be used to control the flow of a coroutine. It could be wrapped in a decorator, but I was thinking it would be simpler to be able to pass it a function to create the ResultCompletionEventArgs in the ctor, The function would then receive the MessengerResult and return a ResultCompletionEventArgs to match the outcome.

Just a thought :)

**Comment by tibel** [comment]
The idea was to keep the MeesngerResult simple and afterwards you decide if you want to cancel:

``` C#
if (message.Result != MessageResult.Yes)
    yield return new CancelResult();
```

**Comment by Geminior** [comment]
Yes I see your point, also in a yes,no,cancel scenario you would likely want to branch the routine off in two different paths on yes and no and only cancel on cancel, which could not be done with what I suggested, so feel free to close again. Next time I'll sleep on it before creating an issue :)
